"""empty message

Revision ID: 08c34f5df417
Revises: 9f3c2a1b7d4e
Create Date: 2026-05-06 14:20:17.739280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '08c34f5df417'
down_revision: Union[str, Sequence[str], None] = '9f3c2a1b7d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('penalty')
    op.drop_table('teammember')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_name'))

    op.drop_table('team')
    op.drop_table('matchscore')
    op.drop_table('tournamentarea')
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athletes_kata_category_id'))
        batch_op.drop_index(batch_op.f('ix_athletes_kumite_category_id'))

    with op.batch_alter_table('match_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_scores_applied_by_id'))
        batch_op.drop_index(batch_op.f('ix_match_scores_judge_id'))

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_aka_id'))
        batch_op.drop_index(batch_op.f('ix_matches_aka_team_id'))
        batch_op.drop_index(batch_op.f('ix_matches_ao_id'))
        batch_op.drop_index(batch_op.f('ix_matches_ao_team_id'))
        batch_op.drop_index(batch_op.f('ix_matches_referee_id'))
        batch_op.drop_index(batch_op.f('ix_matches_tatami_id'))
        batch_op.drop_index(batch_op.f('ix_matches_winner_id'))

    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penalties_given_by_id'))

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_user_id'))

    with op.batch_alter_table('tournament_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_categories_first_place_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_categories_second_place_id'))

    with op.batch_alter_table('tournament_event_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_event_logs_user_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_event_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_event_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tournament_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_categories_second_place_id'), ['second_place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_categories_first_place_id'), ['first_place_id'], unique=False)

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blacklist_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penalties_given_by_id'), ['given_by_id'], unique=False)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_winner_id'), ['winner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_tatami_id'), ['tatami_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_referee_id'), ['referee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_ao_team_id'), ['ao_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_ao_id'), ['ao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_aka_team_id'), ['aka_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_aka_id'), ['aka_id'], unique=False)

    with op.batch_alter_table('match_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_scores_judge_id'), ['judge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_scores_applied_by_id'), ['applied_by_id'], unique=False)

    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athletes_kumite_category_id'), ['kumite_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_athletes_kata_category_id'), ['kata_category_id'], unique=False)

    op.create_table('tournamentarea',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('current_match_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['current_match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchscore',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=False),
    sa.Column('participant', sa.VARCHAR(), nullable=False),
    sa.Column('judge_id', sa.INTEGER(), nullable=False),
    sa.Column('score_value', sa.FLOAT(), nullable=False),
    sa.Column('score_type', sa.VARCHAR(), nullable=False),
    sa.Column('technique_time', sa.INTEGER(), nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['referee.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('dojo', sa.VARCHAR(length=255), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('member_count', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['katacategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_name'), ['name'], unique=1)

    op.create_table('teammember',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.Column('athlete_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('is_reserve', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalty',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=False),
    sa.Column('participant', sa.VARCHAR(), nullable=False),
    sa.Column('penalty_type', sa.VARCHAR(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=False),
    sa.Column('rule_reference', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_accumulated', sa.BOOLEAN(), nullable=False),
    sa.Column('given_by', sa.INTEGER(), nullable=False),
    sa.Column('match_time_seconds', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['given_by'], ['referee.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    # ### end Alembic commands ###
