"""add_is_transitioning_and_tournament_event_logs

Revision ID: 1a07f35b60ef
Revises: 7b8cb37055e9
Create Date: 2026-04-11 13:43:30.116280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1a07f35b60ef"
down_revision: Union[str, Sequence[str], None] = "7b8cb37055e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournament_event_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "event_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "old_status", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "new_status", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tournament_event_logs_tournament_id"),
        "tournament_event_logs",
        ["tournament_id"],
        unique=False,
    )
    op.add_column(
        "tournaments",
        sa.Column(
            "is_transitioning", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tournaments", "is_transitioning")
    op.drop_index(
        op.f("ix_tournament_event_logs_tournament_id"),
        table_name="tournament_event_logs",
    )
    op.drop_table("tournament_event_logs")
    # ### end Alembic commands ###
