"""añadido modelo match

Revision ID: 4b98b66a3e28
Revises: be08d982ef4f
Create Date: 2026-02-10 13:26:28.064726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4b98b66a3e28'
down_revision: Union[str, Sequence[str], None] = 'be08d982ef4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aka_id', sa.Integer(), nullable=False),
    sa.Column('ao_id', sa.Integer(), nullable=False),
    sa.Column('aka_score', sa.Integer(), nullable=False),
    sa.Column('ao_score', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('kata_category_id', sa.Integer(), nullable=True),
    sa.Column('kumite_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aka_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['ao_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['kata_category_id'], ['katacategory.id'], ),
    sa.ForeignKeyConstraint(['kumite_category_id'], ['kumitecategory.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
