"""add new models and update existing

Revision ID: 4eaebbb0b3c6
Revises: 4b98b66a3e28
Create Date: 2026-03-30 15:03:07.005639

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4eaebbb0b3c6"
down_revision: Union[str, Sequence[str], None] = "4b98b66a3e28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournamentarea",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "location", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("current_match_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_match_id"],
            ["match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "password_hash",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "matchscore",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("participant", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("judge_id", sa.Integer(), nullable=False),
        sa.Column("score_value", sa.Float(), nullable=False),
        sa.Column("score_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("technique_time", sa.Integer(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["judge_id"],
            ["referee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "penalty",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("participant", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("penalty_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "reason", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "rule_reference", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("is_accumulated", sa.Boolean(), nullable=False),
        sa.Column("given_by", sa.Integer(), nullable=False),
        sa.Column("match_time_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["given_by"],
            ["referee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dojo", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["katacategory.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_name"), "team", ["name"], unique=True)
    op.create_table(
        "teammember",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_reserve", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "athlete", sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column("athlete", sa.Column("date_of_birth", sa.Date(), nullable=False))
    op.add_column(
        "athlete",
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "athlete",
        sa.Column(
            "belt_rank", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
    )
    op.add_column(
        "athlete",
        sa.Column("dojo", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    )
    op.add_column(
        "athlete",
        sa.Column(
            "nationality", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True
        ),
    )
    op.add_column(
        "athlete",
        sa.Column(
            "license_number", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
    )
    op.add_column("athlete", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column(
        "athlete",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column(
        "athlete",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column("athlete", sa.Column("referee_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_athlete_email"), "athlete", ["email"], unique=True)
    op.create_foreign_key(None, "athlete", "referee", ["referee_id"], ["id"])
    op.drop_column("athlete", "belt")
    op.drop_column("athlete", "age")
    op.add_column("match", sa.Column("round", sa.Integer(), nullable=False))
    op.add_column("match", sa.Column("match_number", sa.Integer(), nullable=False))
    op.add_column("match", sa.Column("position", sa.Integer(), nullable=False))
    op.add_column(
        "match",
        sa.Column("match_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "match", sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column("match", sa.Column("start_time", sa.DateTime(), nullable=True))
    op.add_column("match", sa.Column("end_time", sa.DateTime(), nullable=True))
    op.add_column("match", sa.Column("tatami_id", sa.Integer(), nullable=True))
    op.add_column("match", sa.Column("referee_id", sa.Integer(), nullable=True))
    op.add_column("match", sa.Column("judge_panel_id", sa.Integer(), nullable=True))
    op.add_column(
        "match", sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "match",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.create_foreign_key(None, "match", "referee", ["referee_id"], ["id"])
    op.create_foreign_key(None, "match", "tournamentarea", ["tatami_id"], ["id"])
    op.add_column(
        "referee",
        sa.Column(
            "license_number",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
    )
    op.add_column(
        "referee",
        sa.Column("license_level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "referee",
        sa.Column(
            "tatami_certified", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column("referee", sa.Column("is_available", sa.Boolean(), nullable=False))
    op.add_column(
        "referee",
        sa.Column("dojo", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    )
    op.add_column(
        "referee",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    )
    op.add_column(
        "referee",
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    )
    op.add_column(
        "referee",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.alter_column("referee", "role", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("referee", "license")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("referee", sa.Column("license", sa.VARCHAR(), nullable=True))
    op.alter_column("referee", "role", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("referee", "created_at")
    op.drop_column("referee", "phone")
    op.drop_column("referee", "email")
    op.drop_column("referee", "dojo")
    op.drop_column("referee", "is_available")
    op.drop_column("referee", "tatami_certified")
    op.drop_column("referee", "license_level")
    op.drop_column("referee", "license_number")
    op.drop_constraint(None, "match", type_="foreignkey")
    op.drop_constraint(None, "match", type_="foreignkey")
    op.drop_column("match", "created_at")
    op.drop_column("match", "notes")
    op.drop_column("match", "judge_panel_id")
    op.drop_column("match", "referee_id")
    op.drop_column("match", "tatami_id")
    op.drop_column("match", "end_time")
    op.drop_column("match", "start_time")
    op.drop_column("match", "status")
    op.drop_column("match", "match_type")
    op.drop_column("match", "position")
    op.drop_column("match", "match_number")
    op.drop_column("match", "round")
    op.add_column("athlete", sa.Column("age", sa.INTEGER(), nullable=True))
    op.add_column("athlete", sa.Column("belt", sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, "athlete", type_="foreignkey")
    op.drop_index(op.f("ix_athlete_email"), table_name="athlete")
    op.drop_column("athlete", "referee_id")
    op.drop_column("athlete", "updated_at")
    op.drop_column("athlete", "created_at")
    op.drop_column("athlete", "is_active")
    op.drop_column("athlete", "license_number")
    op.drop_column("athlete", "nationality")
    op.drop_column("athlete", "dojo")
    op.drop_column("athlete", "belt_rank")
    op.drop_column("athlete", "gender")
    op.drop_column("athlete", "date_of_birth")
    op.drop_column("athlete", "email")
    op.drop_table("teammember")
    op.drop_index(op.f("ix_team_name"), table_name="team")
    op.drop_table("team")
    op.drop_table("penalty")
    op.drop_table("matchscore")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("tournamentarea")
    # ### end Alembic commands ###
