"""empty message

Revision ID: 52613ac909db
Revises: 10577f633a38
Create Date: 2026-06-18 09:39:24.403715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '52613ac909db'
down_revision: Union[str, Sequence[str], None] = '10577f633a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_categories', schema=None) as batch_op:
        batch_op.drop_column('flag_count')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_count', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
