"""empty message

Revision ID: 5e8a0525f69e
Revises: 
Create Date: 2026-02-05 14:34:17.100659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5e8a0525f69e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('katacategory',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('min_belt', sa.Integer(), nullable=True),
    sa.Column('max_belt', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('katacategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_katacategory_name'), ['name'], unique=True)

    op.create_table('kumitecategory',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('min_belt', sa.Integer(), nullable=True),
    sa.Column('max_belt', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kumitecategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kumitecategory_name'), ['name'], unique=True)

    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('belt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('kata_category_id', sa.Integer(), nullable=True),
    sa.Column('kumite_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kata_category_id'], ['katacategory.id'], ),
    sa.ForeignKeyConstraint(['kumite_category_id'], ['kumitecategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athlete_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athlete_name'))

    op.drop_table('athlete')
    with op.batch_alter_table('kumitecategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kumitecategory_name'))

    op.drop_table('kumitecategory')
    with op.batch_alter_table('katacategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_katacategory_name'))

    op.drop_table('katacategory')
    op.drop_table('tournament')
    # ### end Alembic commands ###
