"""empty message

Revision ID: 6ff093a8c71f
Revises: 0020687a5500
Create Date: 2026-03-31 22:37:11.493338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6ff093a8c71f'
down_revision: Union[str, Sequence[str], None] = '0020687a5500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('belt_rank', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('dojo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('kata_category_id', sa.Integer(), nullable=True),
    sa.Column('kumite_category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kata_category_id'], ['tournament_categories.id'], ),
    sa.ForeignKeyConstraint(['kumite_category_id'], ['tournament_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('license_number')
    )
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athletes_date_of_birth'), ['date_of_birth'], unique=False)
        batch_op.create_index(batch_op.f('ix_athletes_name'), ['name'], unique=True)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('match_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('aka_id', sa.Integer(), nullable=True),
    sa.Column('ao_id', sa.Integer(), nullable=True),
    sa.Column('aka_score', sa.Integer(), nullable=False),
    sa.Column('ao_score', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('tatami_id', sa.Integer(), nullable=True),
    sa.Column('referee_id', sa.Integer(), nullable=True),
    sa.Column('judge_panel_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['aka_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['ao_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['tournament_categories.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ),
    sa.ForeignKeyConstraint(['tatami_id'], ['tatamis.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_category_id'), ['category_id'], unique=False)

    op.create_table('referees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('license_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('tatami_certified', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dojo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referees_license_number'), ['license_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_referees_name'), ['name'], unique=False)

    op.create_table('tatamis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('current_match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tatamis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tatamis_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('tournament_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('modality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.Column('competition_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bracket_size', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('min_belt_rank', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('max_belt_rank', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('flag_count', sa.Integer(), nullable=True),
    sa.Column('has_bunkai', sa.Boolean(), nullable=False),
    sa.Column('judge_panel_size', sa.Integer(), nullable=False),
    sa.Column('scoring_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_weight_kg', sa.Float(), nullable=True),
    sa.Column('max_weight_kg', sa.Float(), nullable=True),
    sa.Column('match_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('extension_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('has_weight_tolerance', sa.Boolean(), nullable=False),
    sa.Column('weight_tolerance_kg', sa.Float(), nullable=True),
    sa.Column('first_place_id', sa.Integer(), nullable=True),
    sa.Column('second_place_id', sa.Integer(), nullable=True),
    sa.Column('third_place_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['first_place_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['second_place_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_categories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_categories_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('match_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('participant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.Column('score_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technique_time', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['referees.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_scores_match_id'), ['match_id'], unique=False)

    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('given_by_id', sa.Integer(), nullable=False),
    sa.Column('participant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('penalty_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rule_reference', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_accumulated', sa.Boolean(), nullable=False),
    sa.Column('match_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['given_by_id'], ['referees.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penalties_match_id'), ['match_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dojo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tournament_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=False)

    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('venue', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('tatami_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organizing_federation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('viewer_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_start_date'), ['start_date'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_reserve', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('katacategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_katacategory_name'))

    op.drop_table('katacategory')
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athlete_name'))

    op.drop_table('athlete')
    with op.batch_alter_table('kumitecategory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kumitecategory_name'))

    op.drop_table('kumitecategory')
    op.drop_table('tournament')
    op.drop_table('match')
    with op.batch_alter_table('referee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referee_name'))

    op.drop_table('referee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('license', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referee_name'), ['name'], unique=1)

    op.create_table('match',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aka_id', sa.INTEGER(), nullable=False),
    sa.Column('ao_id', sa.INTEGER(), nullable=False),
    sa.Column('aka_score', sa.INTEGER(), nullable=False),
    sa.Column('ao_score', sa.INTEGER(), nullable=False),
    sa.Column('winner_id', sa.INTEGER(), nullable=True),
    sa.Column('kata_category_id', sa.INTEGER(), nullable=True),
    sa.Column('kumite_category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['aka_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['ao_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['kata_category_id'], ['katacategory.id'], ),
    sa.ForeignKeyConstraint(['kumite_category_id'], ['kumitecategory.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('kumitecategory',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('min_age', sa.INTEGER(), nullable=True),
    sa.Column('max_age', sa.INTEGER(), nullable=True),
    sa.Column('min_belt', sa.INTEGER(), nullable=True),
    sa.Column('max_belt', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('weight_kg', sa.FLOAT(), nullable=True),
    sa.Column('first_place', sa.VARCHAR(), nullable=True),
    sa.Column('second_place', sa.VARCHAR(), nullable=True),
    sa.Column('third_place', sa.VARCHAR(), nullable=True),
    sa.Column('fourth_place', sa.VARCHAR(), nullable=True),
    sa.Column('tournament_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kumitecategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kumitecategory_name'), ['name'], unique=1)

    op.create_table('athlete',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('belt', sa.VARCHAR(), nullable=True),
    sa.Column('weight_kg', sa.FLOAT(), nullable=True),
    sa.Column('kata_category_id', sa.INTEGER(), nullable=True),
    sa.Column('kumite_category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['kata_category_id'], ['katacategory.id'], ),
    sa.ForeignKeyConstraint(['kumite_category_id'], ['kumitecategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athlete', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athlete_name'), ['name'], unique=1)

    op.create_table('katacategory',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('min_age', sa.INTEGER(), nullable=True),
    sa.Column('max_age', sa.INTEGER(), nullable=True),
    sa.Column('min_belt', sa.INTEGER(), nullable=True),
    sa.Column('max_belt', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_place', sa.VARCHAR(), nullable=True),
    sa.Column('second_place', sa.VARCHAR(), nullable=True),
    sa.Column('third_place', sa.VARCHAR(), nullable=True),
    sa.Column('fourth_place', sa.VARCHAR(), nullable=True),
    sa.Column('tournament_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('katacategory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_katacategory_name'), ['name'], unique=1)

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_athlete_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_start_date'))

    op.drop_table('tournaments')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_category_id'))

    op.drop_table('teams')
    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penalties_match_id'))

    op.drop_table('penalties')
    with op.batch_alter_table('match_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_scores_match_id'))

    op.drop_table('match_scores')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tournament_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_categories_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_categories_name'))

    op.drop_table('tournament_categories')
    with op.batch_alter_table('tatamis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tatamis_tournament_id'))

    op.drop_table('tatamis')
    with op.batch_alter_table('referees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referees_name'))
        batch_op.drop_index(batch_op.f('ix_referees_license_number'))

    op.drop_table('referees')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_category_id'))

    op.drop_table('matches')
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athletes_name'))
        batch_op.drop_index(batch_op.f('ix_athletes_date_of_birth'))

    op.drop_table('athletes')
    # ### end Alembic commands ###
