"""add tournament fields and status enum

Revision ID: 76ed8bac3e8b
Revises: 4eaebbb0b3c6
Create Date: 2026-03-30 15:13:31.042726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "76ed8bac3e8b"
down_revision: Union[str, Sequence[str], None] = "4eaebbb0b3c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tournament", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("venue", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )
        batch_op.add_column(sa.Column("start_date", sa.Date(), nullable=False))
        batch_op.add_column(sa.Column("end_date", sa.Date(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "organizing_federation",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "license_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(sa.Column("tatami_count", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("is_public", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "viewer_code", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True
            )
        )
        batch_op.add_column(sa.Column("created_by", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default="CURRENT_TIMESTAMP",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default="CURRENT_TIMESTAMP",
                nullable=False,
            )
        )
        batch_op.create_foreign_key(
            "fk_tournament_created_by_user", "user", ["created_by"], ["id"]
        )
        batch_op.drop_column("date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tournament", schema=None) as batch_op:
        batch_op.add_column(sa.Column("date", sa.DATE(), nullable=False))
        batch_op.drop_constraint("fk_tournament_created_by_user", type_="foreignkey")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("created_by")
        batch_op.drop_column("viewer_code")
        batch_op.drop_column("is_public")
        batch_op.drop_column("tatami_count")
        batch_op.drop_column("license_number")
        batch_op.drop_column("organizing_federation")
        batch_op.drop_column("end_date")
        batch_op.drop_column("start_date")
        batch_op.drop_column("venue")
        batch_op.drop_column("description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tournament", sa.Column("date", sa.DATE(), nullable=False))
    op.drop_constraint(None, "tournament", type_="foreignkey")
    op.drop_column("tournament", "updated_at")
    op.drop_column("tournament", "created_at")
    op.drop_column("tournament", "created_by")
    op.drop_column("tournament", "viewer_code")
    op.drop_column("tournament", "is_public")
    op.drop_column("tournament", "tatami_count")
    op.drop_column("tournament", "license_number")
    op.drop_column("tournament", "organizing_federation")
    op.drop_column("tournament", "end_date")
    op.drop_column("tournament", "start_date")
    op.drop_column("tournament", "venue")
    op.drop_column("tournament", "description")
    # ### end Alembic commands ###
