"""empty message

Revision ID: be08d982ef4f
Revises: 55348386db7b
Create Date: 2026-02-10 13:13:39.787261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'be08d982ef4f'
down_revision: Union[str, Sequence[str], None] = '55348386db7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('katacategory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('third_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('fourth_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('kumitecategory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('second_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('third_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('fourth_place', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kumitecategory', schema=None) as batch_op:
        batch_op.drop_column('fourth_place')
        batch_op.drop_column('third_place')
        batch_op.drop_column('second_place')
        batch_op.drop_column('first_place')

    with op.batch_alter_table('katacategory', schema=None) as batch_op:
        batch_op.drop_column('fourth_place')
        batch_op.drop_column('third_place')
        batch_op.drop_column('second_place')

    # ### end Alembic commands ###
