"""initial

Revision ID: c245880d6c18
Revises:
Create Date: 2026-03-31 20:53:01.779382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c245880d6c18"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("license", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_referee_name"), "referee", ["name"], unique=True)
    op.create_table(
        "tournament",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "katacategory",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("min_age", sa.Integer(), nullable=True),
        sa.Column("max_age", sa.Integer(), nullable=True),
        sa.Column("min_belt", sa.Integer(), nullable=True),
        sa.Column("max_belt", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_place", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("second_place", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("third_place", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fourth_place", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tournament_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_katacategory_name"), "katacategory", ["name"], unique=True)
    op.create_table(
        "kumitecategory",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("min_age", sa.Integer(), nullable=True),
        sa.Column("max_age", sa.Integer(), nullable=True),
        sa.Column("min_belt", sa.Integer(), nullable=True),
        sa.Column("max_belt", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("first_place", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("second_place", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("third_place", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fourth_place", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tournament_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kumitecategory_name"), "kumitecategory", ["name"], unique=True
    )
    op.create_table(
        "athlete",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("belt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("kata_category_id", sa.Integer(), nullable=True),
        sa.Column("kumite_category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["kata_category_id"],
            ["katacategory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kumite_category_id"],
            ["kumitecategory.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_athlete_name"), "athlete", ["name"], unique=True)
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dojo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["katacategory.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=True)
    op.create_table(
        "match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aka_id", sa.Integer(), nullable=False),
        sa.Column("ao_id", sa.Integer(), nullable=False),
        sa.Column("aka_score", sa.Integer(), nullable=False),
        sa.Column("ao_score", sa.Integer(), nullable=False),
        sa.Column("winner_id", sa.Integer(), nullable=True),
        sa.Column("kata_category_id", sa.Integer(), nullable=True),
        sa.Column("kumite_category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["aka_id"],
            ["athlete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ao_id"],
            ["athlete.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kata_category_id"],
            ["katacategory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kumite_category_id"],
            ["kumitecategory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["athlete.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match")
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_athlete_name"), table_name="athlete")
    op.drop_table("athlete")
    op.drop_index(op.f("ix_kumitecategory_name"), table_name="kumitecategory")
    op.drop_table("kumitecategory")
    op.drop_index(op.f("ix_katacategory_name"), table_name="katacategory")
    op.drop_table("katacategory")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("tournament")
    op.drop_index(op.f("ix_referee_name"), table_name="referee")
    op.drop_table("referee")
    # ### end Alembic commands ###
