"""empty message

Revision ID: c80c22032ebc
Revises: 3b2f6d4a9c10
Create Date: 2026-05-07 12:07:14.801975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c80c22032ebc'
down_revision: Union[str, Sequence[str], None] = '3b2f6d4a9c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kata_judge_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('performer_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('participant', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('flag_vote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_flag_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['referees.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kata_judge_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kata_judge_scores_judge_id'), ['judge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kata_judge_scores_match_id'), ['match_id'], unique=False)

    op.create_table('kata_round_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('victory_points', sa.Integer(), nullable=False),
    sa.Column('votes_received', sa.Integer(), nullable=False),
    sa.Column('needs_extra_kata', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kata_round_standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kata_round_standings_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kata_round_standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kata_round_standings_match_id'))

    op.drop_table('kata_round_standings')
    with op.batch_alter_table('kata_judge_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kata_judge_scores_match_id'))
        batch_op.drop_index(batch_op.f('ix_kata_judge_scores_judge_id'))

    op.drop_table('kata_judge_scores')
    # ### end Alembic commands ###
