"""empty message

Revision ID: effb5c40a98c
Revises: a8c4641d867d
Create Date: 2026-04-14 10:52:50.419793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'effb5c40a98c'
down_revision: Union[str, Sequence[str], None] = 'a8c4641d867d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kata_judge_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kata_judge_scores_judge_id'))
        batch_op.drop_index(batch_op.f('ix_kata_judge_scores_match_id'))

    op.drop_table('kata_judge_scores')
    with op.batch_alter_table('kata_round_standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kata_round_standings_match_id'))

    op.drop_table('kata_round_standings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kata_round_standings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=False),
    sa.Column('athlete_id', sa.INTEGER(), nullable=True),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.Column('victory_points', sa.INTEGER(), nullable=False),
    sa.Column('votes_received', sa.INTEGER(), nullable=False),
    sa.Column('needs_extra_kata', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kata_round_standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kata_round_standings_match_id'), ['match_id'], unique=False)

    op.create_table('kata_judge_scores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('judge_id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=False),
    sa.Column('performer_id', sa.INTEGER(), nullable=True),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.Column('participant', sa.VARCHAR(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('flag_vote', sa.VARCHAR(), nullable=True),
    sa.Column('is_flag_mode', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['judge_id'], ['referees.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kata_judge_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kata_judge_scores_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kata_judge_scores_judge_id'), ['judge_id'], unique=False)

    # ### end Alembic commands ###
