"""add kumite scoring fields

Revision ID: f0988d9c3f59
Revises: 1a07f35b60ef
Create Date: 2026-04-13 16:39:27.605737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0988d9c3f59"
down_revision: Union[str, Sequence[str], None] = "1a07f35b60ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(inspector: sa.Inspector, table_name: str, column_name: str) -> bool:
    """Retorna True si la tabla contiene la columna indicada."""
    columns = {column["name"] for column in inspector.get_columns(table_name)}
    return column_name in columns


def _has_fk_for_column(
    inspector: sa.Inspector, table_name: str, column_name: str
) -> bool:
    """Retorna True si existe FK sobre la columna indicada."""
    foreign_keys = inspector.get_foreign_keys(table_name)
    return any(fk.get("constrained_columns") == [column_name] for fk in foreign_keys)


def _add_match_score_applied_by_column(inspector: sa.Inspector) -> None:
    """Agrega columna applied_by_id en match_scores si no existe."""
    if not _has_column(inspector, "match_scores", "applied_by_id"):
        op.add_column(
            "match_scores",
            sa.Column("applied_by_id", sa.Integer(), nullable=True),
        )


def _add_match_score_applied_by_fk(inspector: sa.Inspector) -> None:
    """Agrega FK users.id para match_scores.applied_by_id en SQLite."""
    if not _has_fk_for_column(inspector, "match_scores", "applied_by_id"):
        with op.batch_alter_table("match_scores", recreate="always") as batch_op:
            batch_op.create_foreign_key(
                "fk_match_scores_applied_by_id_users",
                "users",
                ["applied_by_id"],
                ["id"],
            )


def _add_match_column_if_missing(
    inspector: sa.Inspector,
    column_name: str,
    column_type: sa.types.TypeEngine,
) -> None:
    """Agrega columna NOT NULL con server_default=0 si no existe."""
    if _has_column(inspector, "matches", column_name):
        return

    op.add_column(
        "matches",
        sa.Column(
            column_name,
            column_type,
            nullable=False,
            server_default=sa.text("0"),
        ),
    )


def _drop_match_column_if_exists(inspector: sa.Inspector, column_name: str) -> None:
    """Elimina columna de matches si existe."""
    if _has_column(inspector, "matches", column_name):
        op.drop_column("matches", column_name)


def _drop_match_score_applied_by_fk_if_exists(inspector: sa.Inspector) -> None:
    """Elimina FK match_scores.applied_by_id si existe."""
    if _has_fk_for_column(inspector, "match_scores", "applied_by_id"):
        with op.batch_alter_table("match_scores", recreate="always") as batch_op:
            batch_op.drop_constraint(
                "fk_match_scores_applied_by_id_users",
                type_="foreignkey",
            )


def _drop_match_score_applied_by_column_if_exists(inspector: sa.Inspector) -> None:
    """Elimina columna match_scores.applied_by_id si existe."""
    if _has_column(inspector, "match_scores", "applied_by_id"):
        op.drop_column("match_scores", "applied_by_id")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    _add_match_score_applied_by_column(inspector)
    inspector = sa.inspect(bind)
    _add_match_score_applied_by_fk(inspector)

    inspector = sa.inspect(bind)
    _add_match_column_if_missing(inspector, "aka_senshu", sa.Boolean())
    _add_match_column_if_missing(inspector, "ao_senshu", sa.Boolean())
    _add_match_column_if_missing(inspector, "aka_ippon_count", sa.Integer())
    _add_match_column_if_missing(inspector, "ao_ippon_count", sa.Integer())
    _add_match_column_if_missing(inspector, "aka_waza_ari_count", sa.Integer())
    _add_match_column_if_missing(inspector, "ao_waza_ari_count", sa.Integer())
    _add_match_column_if_missing(inspector, "aka_yuko_count", sa.Integer())
    _add_match_column_if_missing(inspector, "ao_yuko_count", sa.Integer())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    _drop_match_column_if_exists(inspector, "ao_yuko_count")
    _drop_match_column_if_exists(inspector, "aka_yuko_count")
    _drop_match_column_if_exists(inspector, "ao_waza_ari_count")
    _drop_match_column_if_exists(inspector, "aka_waza_ari_count")
    _drop_match_column_if_exists(inspector, "ao_ippon_count")
    _drop_match_column_if_exists(inspector, "aka_ippon_count")
    _drop_match_column_if_exists(inspector, "ao_senshu")
    _drop_match_column_if_exists(inspector, "aka_senshu")

    inspector = sa.inspect(bind)
    _drop_match_score_applied_by_fk_if_exists(inspector)
    inspector = sa.inspect(bind)
    _drop_match_score_applied_by_column_if_exists(inspector)
    # ### end Alembic commands ###
