"""empty message

Revision ID: fe678c4071ac
Revises: b1f4a2d9c8e1
Create Date: 2026-04-18 14:19:10.983284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe678c4071ac'
down_revision: Union[str, Sequence[str], None] = 'b1f4a2d9c8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_tatami_start_time'))

    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penalties_match_participant'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penalties_match_participant'), ['match_id', 'participant'], unique=False)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_tatami_start_time'), ['tatami_id', 'start_time'], unique=False)

    # ### end Alembic commands ###
